### ISSUE TITLE
details 

### ISSUE THREAD

**Issue by 3073** [Nikhil-Kasukurthi/Counting-people-video#1]
It is really good.
but when I test it on sample video that contain 15 people it outputs different value based on the jump used in the "time_ " variable. if I make the jump 5 for a 49 second video it output less than 15 people and if I take a jump of 1 it outputs 17 people.
I think a tracker is required like sort. 
question: how to implement this for webcam?

**Comment by Nikhil-Kasukurthi** [comment]
Yeah, if you are looking for a really accurate model I would suggest you to
create a face detection module that can keep track of all the detected
people. Or else try to fine tune the "time_" if you know the ground truth
and see what works best.
Coming to the implementation of webcam, just give the --path as 0. Open CV
give the webcam feed if the input is 0.

**Comment by 3073** [comment]
thank you for real

**Comment by Nikhil-Kasukurthi** [comment]
If you need any more help, just re-open this issue or create another issue. Cheers/
